### ISSUE TITLE
Unable to run nf -h

### ISSUE THREAD

**Issue by ablesofts92** [0xKayala/NucleiFuzzer#18]
Followed the installation procedure. Says it installed successfully.. however running nf -h says I have no permission but running with sudo also does not work .

Bellow is the exact command

[krakensub@centos-8gb-pa tools]$ sudo git clone https://github.com/0xKayala/NucleiFuzzer.git
Cloning into 'NucleiFuzzer'...
remote: Enumerating objects: 197, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 197 (delta 43), reused 75 (delta 28), pack-reused 101
Receiving objects: 100% (197/197), 51.95 KiB | 1.73 MiB/s, done.
Resolving deltas: 100% (63/63), done.
[krakensub@centos-8gb-pa tools]$ cd NucleiFuzzer/
[krakensub@centos-8gb-pa NucleiFuzzer]$ sudo chmod +x install.sh
[krakensub@centos-8gb-pa NucleiFuzzer]$ ./install.sh
NucleiFuzzer has been installed successfully! Now Enter the command 'nf' to run the tool.
[krakensub@centos-8gb-pa NucleiFuzzer]$ nf -h
-bash: /usr/local/bin/nf: Permission denied
[krakensub@centos-8gb-pa NucleiFuzzer]$ sudo nf -h
sudo: nf: command not found
[krakensub@centos-8gb-pa NucleiFuzzer]$ sudo ./install.sh
mv: cannot stat 'NucleiFuzzer.sh': No such file or directory
NucleiFuzzer has been installed successfully! Now Enter the command 'nf' to run the tool.

**Comment by 0xKayala** [comment]
I have just installed it now and it is working fine for me. May be there is some issue from your end. Login into this website "https://shell.cloud.google.com" with your google account and try to install the NucleiFuzzer tool in it and check so that you can know whether the issue is with your machine or the tool.

![image](https://github.com/0xKayala/NucleiFuzzer/assets/16838353/1dd7f1b6-f51f-4be4-9ae1-3265803c9401)

**Comment by ablesofts92** [comment]
Tnx for your quick response. When I run the same command as you did as root, it installs and works fine.however, as any other sudo user, it does not work. I guess will just use it as root
